services:
  nodejs:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    container_name: nodejs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - placmitu_node_modules:/var/www/app/node_modules

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - nodejs

volumes:
  placmitu_node_modules:

networks:
  shared_dev_network:
    external: true
